repos:
  - repo: local
    hooks:
      - id: format-src
        name: Format src
        entry: black src
        language: python
        pass_filenames: false
      - id: lint-src
        name: Lint src
        entry: ruff src
        language: python
        pass_filenames: false
      - id: type-check-src
        name: Type Check src
        entry: mypy src
        language: python
        pass_filenames: false
